import os from 'node:os'
import path from 'node:path'
import { show } from '@nan0web/ui'
import { ModelAsApp } from '@nan0web/ui-cli'
import { IndexWorkspaceApp } from './IndexWorkspaceApp.js'
import { DBFS } from '@nan0web/db-fs'

/**
 * SyncWorkspaceApp — command to synchronize workspace state and re-index agents.
 */
export class SyncWorkspaceApp extends ModelAsApp {
	static alias = 'sync'
	static UI = {
		syncStarted: 'Starting global synchronization across all editors...',
		agentsUpdated: 'Global agent index updated: {total} agents found.',
		workflowsSynced: 'Workflows & Rules synced to {target}',
		done: 'All AI assistants (Antigravity, VSCode, etc.) are now synchronized.',
	}

	/**
	 * @returns {AsyncGenerator<any, any, any>}
	 */
	async *run() {
		const { show, ask } = await import('@nan0web/ui')

		if (this.help) {
			const content = this.generateHelp()
			if (this.raw) {
				yield show(content, 'info', /** @type {any} */ ({ format: 'markdown', raw: true }))
				return
			}
			const title = /** @type {any} */ (this.constructor).UI?.title || 'Help'
			yield ask('help', { content, title: `${title} Help`, hint: 'content-viewer' })
			return
		}

		const workspaceRoot = /** @type {any} */ (this._).workspaceRoot || process.cwd()
		const db = new DBFS({ root: workspaceRoot })

		yield show(SyncWorkspaceApp.UI.syncStarted, 'info')

		// 1. Re-index Agents (Global Registry)
		const indexer = new IndexWorkspaceApp({ silent: true, agents: true }, { db, workspaceRoot })
		yield* indexer.run()

		// 2. Propagate Workflows & Rules to Antigravity Global Config
		//    Reads nan0web_agents.index.nan0 (generated by step 1) and collects
		//    all unique workflow files from every registered package/app.
		const antigravityGlobal = path.join(os.homedir(), '.gemini/antigravity/global_workflows')
		const vscodeGlobal = path.join(os.homedir(), '.vscode/extensions/nan0web/workflows')

		const syncedPaths = []

		try {
			db.mount('antigravity', new DBFS({ root: antigravityGlobal }))
			db.mount('vscode', new DBFS({ root: vscodeGlobal }))

			// Load agent index (source of truth for all workflow paths)
			const agentIndex = await db.loadDocument('nan0web_agents.index.nan0').catch(() => null)

			// Load store to resolve package dirs
			const storeDir = path.join(os.homedir(), '.nan0web/store')
			const storeDb = new DBFS({ root: workspaceRoot })
			storeDb.mount('store', new DBFS({ root: storeDir }))
			const packageDirs = new Map()
			for (const s of ['store/nan0web_store.csv', 'store/nan0web_store.local.csv']) {
				const rows = await storeDb.loadDocumentAs('.csv', s).catch(() => null)
				if (Array.isArray(rows)) {
					for (const row of rows) {
						if (row.name && row.path) {
							// Use lowercase for case-insensitive matching
							packageDirs.set(row.name.toLowerCase(), row.path)
						}
					}
				}
			}

			// Collect unique workflow files from agent index
			const workflowFiles = new Map() // filename → absolute resolved path

			// 2a. Fallback: Scan all known packages for workflows even if not in agent index
			for (const [pkgName, pkgPath] of packageDirs) {
				try {
					const workflowsDir = path.join(pkgPath, 'src/agents/workflows')
					const files = await db.listDir(workflowsDir).catch(() => [])
					for (const file of files) {
						if (file.name.endsWith('.md')) {
							workflowFiles.set(file.name, path.join(workflowsDir, file.name))
						}
					}
				} catch (e) {}
			}

			// 2b. Explicit Registration (Agent Index)
			if (agentIndex && Array.isArray(agentIndex.agents)) {
				for (const agent of agentIndex.agents) {
					if (!agent.package || !Array.isArray(agent.workflows)) continue

					const pkgDir = packageDirs.get(agent.package.toLowerCase())
					if (!pkgDir) continue

					for (const wfPath of agent.workflows) {
						if (!wfPath) continue
						const fileName = path.basename(wfPath)
						const fullPath = path.join(pkgDir, wfPath)
						workflowFiles.set(fileName, fullPath)
					}
				}
			}

			// Sync collected workflows to targets
			for (const [fileName, filePath] of workflowFiles) {
				const content = await db.loadDocumentAs('.txt', filePath).catch(() => null)
				if (content !== undefined && content !== null) {
					await db.saveDocument(`antigravity/${fileName}`, content)
					try {
						await db.saveDocument(`vscode/${fileName}`, content)
					} catch (e) {}
				}
			}

			syncedPaths.push(`· Antigravity: ${antigravityGlobal}`)
			try {
				const vsFiles = await db.listDir('vscode')
				if (vsFiles.length > 0) syncedPaths.push(`· VSCode: ${vscodeGlobal}`)
			} catch (e) {}
		} catch (e) {
			const msg = e instanceof Error ? e.message : String(e)
			yield show(`⚠️ Failed to sync some workflows: ${msg}`, 'error')
		}

		// 3. Update Global Context
		const globalConfigDir = path.join(os.homedir(), '.nan0web')
		db.mount('global', new DBFS({ root: globalConfigDir }))
		await db.saveDocument('global/context.nan0', {
			lastWorkspace: workspaceRoot,
			lastSync: new Date().toISOString(),
		})

		syncedPaths.push(`· AI Context: ${path.join(globalConfigDir, 'context.nan0')}`)

		yield show(SyncWorkspaceApp.UI.done, 'success')
		for (const p of syncedPaths) {
			yield show(p, 'info')
		}
	}
}
